import 'dart:io';
import 'package:path/path.dart' as p;

import '../../projects/domain/project.dart';
import '../domain/agent_artifact.dart';
import '../domain/recording.dart';

/// Scans a project repository and note vault for artifacts generated by agents
/// or linked to a specific capture.
class AgentArtifactScanner {
  const AgentArtifactScanner();

  /// Scans for artifacts for [recording] within [project]'s repository and optional [vaultDirectory].
  Future<List<AgentArtifact>> scanForCapture({
    required Recording recording,
    required Project project,
    Directory? vaultDirectory,
  }) async {
    final Map<String, AgentArtifact> results = <String, AgentArtifact>{};
    final String captureId = recording.id;

    // 1. Scan `.agent-tasks/` in project repository
    final String repoPath = project.repoPath.trim();
    if (repoPath.isNotEmpty) {
      final Directory agentTasksDir = Directory(p.join(repoPath, '.agent-tasks'));
      if (await agentTasksDir.exists()) {
        try {
          await for (final FileSystemEntity entity in agentTasksDir.list(recursive: true)) {
            if (entity is! File) continue;
            final String fileName = p.basename(entity.path);

            // Skip original task brief file: <captureId>.md
            if (fileName == '$captureId.md') continue;

            // Direct result file: <captureId>-result.md or <captureId>-*.md or inside <captureId>/
            final bool isDirectResult = fileName.startsWith('$captureId-') ||
                p.split(p.relative(entity.path, from: agentTasksDir.path)).contains(captureId);

            if (isDirectResult && fileName.endsWith('.md')) {
              final AgentArtifact? artifact = await _parseMarkdownArtifact(
                file: entity,
                captureId: captureId,
                defaultKind: AgentArtifactKind.resultNote,
              );
              if (artifact != null) {
                results[artifact.path] = artifact;
              }
            }
          }
        } catch (_) {
          // Swallow file system errors gracefully
        }
      }

      // 2. Scan project repo markdown files for `capture-id: <captureId>`
      try {
        final Directory repoDir = Directory(repoPath);
        if (await repoDir.exists()) {
          await for (final FileSystemEntity entity in repoDir.list(recursive: false)) {
            if (entity is File && entity.path.endsWith('.md')) {
              final AgentArtifact? artifact = await _checkFileForCaptureId(
                file: entity,
                captureId: captureId,
              );
              if (artifact != null) {
                results[artifact.path] = artifact;
              }
            }
          }
        }
      } catch (_) {}
    }

    // 3. Scan Vault directory if present
    if (vaultDirectory != null && await vaultDirectory.exists()) {
      try {
        await for (final FileSystemEntity entity in vaultDirectory.list(recursive: true)) {
          if (entity is File && entity.path.endsWith('.md')) {
            // `.obsidian`, `.trash`, `.git` — machinery of whatever application
            // owns the vault, never a note an agent wrote. Walking them costs a
            // read per file and can only produce false positives.
            final bool hidden = p
                .split(p.relative(entity.path, from: vaultDirectory.path))
                .any((String segment) => segment.startsWith('.'));
            if (hidden) continue;

            final AgentArtifact? artifact = await _checkFileForCaptureId(
              file: entity,
              captureId: captureId,
            );
            if (artifact != null) {
              results[artifact.path] = artifact;
            }
          }
        }
      } catch (_) {}
    }

    // Preserve existing manually linked artifacts if they still exist on disk
    for (final AgentArtifact existing in recording.artifacts) {
      if (!results.containsKey(existing.path)) {
        if (await File(existing.path).exists()) {
          results[existing.path] = existing;
        }
      }
    }

    final List<AgentArtifact> list = results.values.toList();
    list.sort((AgentArtifact a, AgentArtifact b) => b.updatedAt.compareTo(a.updatedAt));
    return list;
  }

  Future<AgentArtifact?> _checkFileForCaptureId({
    required File file,
    required String captureId,
  }) async {
    try {
      final String content = await file.readAsString();
      // Our own vault mirror carries the capture id in its front matter, so
      // without this every mirrored capture listed *itself* as an artifact —
      // the note this app wrote, presented back as something an agent produced.
      // `capture-hash` is the claim `MarkdownNoteVault` makes about a file it
      // owns, and it is the only provenance either class has.
      if (_isOwnVaultMirror(content)) return null;
      if (content.contains('capture-id: $captureId') ||
          content.contains('capture-id: "$captureId"') ||
          content.contains('parent-capture: $captureId')) {
        return _parseMarkdownArtifact(
          file: file,
          captureId: captureId,
          defaultKind: AgentArtifactKind.connectedNote,
        );
      }
    } catch (_) {}
    return null;
  }

  /// Whether [content] is a note `MarkdownNoteVault` wrote, judged the same way
  /// that class judges it: a `capture-hash` key inside the front matter block.
  /// The hash itself is not recomputed here — this only has to tell our own
  /// mirror apart from an agent's note, not decide whether it was since edited.
  static bool _isOwnVaultMirror(String content) {
    if (!content.startsWith('---\n')) return false;
    final int end = content.indexOf('\n---\n', 3);
    if (end < 0) return false;
    return content
        .substring(4, end + 1)
        .split('\n')
        .any((String line) => line.trimLeft().startsWith('capture-hash:'));
  }

  Future<AgentArtifact?> _parseMarkdownArtifact({
    required File file,
    required String captureId,
    required AgentArtifactKind defaultKind,
  }) async {
    try {
      final FileStat stat = await file.stat();
      final String content = await file.readAsString();
      String title = p.basenameWithoutExtension(file.path);

      // Extract title from H1 if present
      final RegExp titleReg = RegExp(r'^#\s+(.+)$', multiLine: true);
      final Match? titleMatch = titleReg.firstMatch(content);
      if (titleMatch != null) {
        title = titleMatch.group(1)!.trim();
      }

      // Generate snippet
      final String snippet = content
          .replaceAll(RegExp(r'^---[\s\S]*?---'), '')
          .replaceAll(RegExp(r'#+\s+'), '')
          .trim();
      final String preview = snippet.length > 200
          ? '${snippet.substring(0, 200)}…'
          : snippet;

      return AgentArtifact(
        id: file.path,
        captureId: captureId,
        title: title,
        path: file.path,
        updatedAt: stat.modified,
        kind: defaultKind,
        snippet: preview.isNotEmpty ? preview : null,
      );
    } catch (_) {
      return null;
    }
  }
}
