/// Kind of artifact produced by an agent or linked to a capture.
enum AgentArtifactKind {
  /// Primary result/summary note generated by the agent (e.g. `.agent-tasks/<id>-result.md`).
  resultNote,

  /// Connected markdown note in vault or project repository.
  connectedNote,

  /// Output or modified file created during task execution.
  modifiedFile;

  static AgentArtifactKind? fromName(String? name) {
    for (final AgentArtifactKind kind in AgentArtifactKind.values) {
      if (kind.name == name) return kind;
    }
    return null;
  }
}

/// An artifact produced by an agent or attached as a connected note to a capture.
class AgentArtifact {
  const AgentArtifact({
    required this.id,
    required this.captureId,
    required this.title,
    required this.path,
    required this.updatedAt,
    this.kind = AgentArtifactKind.resultNote,
    this.snippet,
  });

  final String id;
  final String captureId;
  final String title;

  /// Absolute or relative path to the artifact file.
  final String path;

  final DateTime updatedAt;
  final AgentArtifactKind kind;
  final String? snippet;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'id': id,
        'captureId': captureId,
        'title': title,
        'path': path,
        'updatedAt': updatedAt.toIso8601String(),
        'kind': kind.name,
        if (snippet != null) 'snippet': snippet,
      };

  static AgentArtifact? fromJson(Object? json) {
    if (json is! Map<String, dynamic>) return null;
    final Object? id = json['id'];
    final Object? captureId = json['captureId'];
    final Object? title = json['title'];
    final Object? path = json['path'];
    final Object? updatedAt = json['updatedAt'];
    final Object? kindName = json['kind'];
    if (id is! String ||
        captureId is! String ||
        title is! String ||
        path is! String ||
        updatedAt is! String) {
      return null;
    }
    final DateTime? parsedDate = DateTime.tryParse(updatedAt);
    if (parsedDate == null) return null;

    final AgentArtifactKind kind =
        AgentArtifactKind.fromName(kindName as String?) ??
            AgentArtifactKind.resultNote;

    return AgentArtifact(
      id: id,
      captureId: captureId,
      title: title,
      path: path,
      updatedAt: parsedDate,
      kind: kind,
      snippet: json['snippet'] is String ? json['snippet'] as String : null,
    );
  }

  static List<AgentArtifact> listFromJson(Object? json) {
    if (json is! List) return const <AgentArtifact>[];
    return json
        .map(AgentArtifact.fromJson)
        .whereType<AgentArtifact>()
        .toList(growable: false);
  }
}
